"""
Inference reporting and reproducibility utilities.
"""

from pathlib import Path

import numpy as np
import pandas as pd

from src.utils.io import file_size_mb


def compare_prediction_outputs(
    reference_predictions,
    candidate_predictions,
    prediction_column="prediction",
    grain_columns=None,
    id_column="id",
    absolute_tolerance=1e-6,
    total_tolerance=1e-4,
):
    """
    Compare reference and candidate prediction outputs.

    Parameters
    ----------
    reference_predictions : pandas.DataFrame
        Reference prediction output.
    candidate_predictions : pandas.DataFrame
        Candidate prediction output generated by the src pipeline.
    prediction_column : str
        Prediction column name.
    grain_columns : list of str, optional
        Prediction grain columns.
    id_column : str
        Optional id column.
    absolute_tolerance : float
        Maximum allowed row-level absolute difference.
    total_tolerance : float
        Maximum allowed total prediction difference.

    Returns
    -------
    tuple
        Comparison summary dataframe and row-level comparison dataframe.
    """
    reference = reference_predictions.copy()
    candidate = candidate_predictions.copy()

    if prediction_column not in reference.columns:
        raise ValueError(
            f"Reference predictions are missing prediction column: {prediction_column}"
        )

    if prediction_column not in candidate.columns:
        raise ValueError(
            f"Candidate predictions are missing prediction column: {prediction_column}"
        )

    if id_column in reference.columns and id_column in candidate.columns:
        comparison_keys = [id_column]
    elif grain_columns is not None and set(grain_columns).issubset(reference.columns) and set(grain_columns).issubset(candidate.columns):
        comparison_keys = list(grain_columns)
    else:
        raise ValueError(
            "Unable to determine comparison keys. "
            "Expected a shared id column or shared prediction grain columns."
        )

    reference_subset = reference[comparison_keys + [prediction_column]].copy()
    candidate_subset = candidate[comparison_keys + [prediction_column]].copy()

    reference_subset = reference_subset.rename(
        columns={prediction_column: "prediction_reference"}
    )

    candidate_subset = candidate_subset.rename(
        columns={prediction_column: "prediction_candidate"}
    )

    row_comparison = reference_subset.merge(
        candidate_subset,
        on=comparison_keys,
        how="outer",
        validate="one_to_one",
        indicator=True,
    )

    row_comparison["prediction_abs_diff"] = (
        row_comparison["prediction_candidate"]
        - row_comparison["prediction_reference"]
    ).abs()

    row_comparison["prediction_diff"] = (
        row_comparison["prediction_candidate"]
        - row_comparison["prediction_reference"]
    )

    missing_reference_rows = int((row_comparison["_merge"] == "right_only").sum())
    missing_candidate_rows = int((row_comparison["_merge"] == "left_only").sum())
    matched_rows = int((row_comparison["_merge"] == "both").sum())

    reference_total = float(reference[prediction_column].sum())
    candidate_total = float(candidate[prediction_column].sum())
    total_difference = candidate_total - reference_total
    total_absolute_difference = abs(total_difference)

    max_absolute_difference = float(row_comparison["prediction_abs_diff"].max())
    mean_absolute_difference = float(row_comparison["prediction_abs_diff"].mean())

    row_level_within_tolerance = bool(
        max_absolute_difference <= absolute_tolerance
    )

    total_within_tolerance = bool(
        total_absolute_difference <= total_tolerance
    )

    summary_records = [
        {
            "check": "same_row_count",
            "passed": len(reference) == len(candidate),
            "critical": True,
            "details": f"Reference rows: {len(reference)}; candidate rows: {len(candidate)}",
        },
        {
            "check": "all_rows_matched",
            "passed": missing_reference_rows == 0 and missing_candidate_rows == 0,
            "critical": True,
            "details": (
                f"Matched rows: {matched_rows}; "
                f"missing reference rows: {missing_reference_rows}; "
                f"missing candidate rows: {missing_candidate_rows}"
            ),
        },
        {
            "check": "row_level_predictions_within_tolerance",
            "passed": row_level_within_tolerance,
            "critical": True,
            "details": (
                f"Max absolute difference: {max_absolute_difference}; "
                f"tolerance: {absolute_tolerance}"
            ),
        },
        {
            "check": "total_prediction_within_tolerance",
            "passed": total_within_tolerance,
            "critical": True,
            "details": (
                f"Reference total: {reference_total}; "
                f"candidate total: {candidate_total}; "
                f"absolute difference: {total_absolute_difference}; "
                f"tolerance: {total_tolerance}"
            ),
        },
        {
            "check": "comparison_key_selected",
            "passed": True,
            "critical": False,
            "details": f"Comparison keys: {comparison_keys}",
        },
        {
            "check": "mean_absolute_difference_recorded",
            "passed": True,
            "critical": False,
            "details": f"Mean absolute difference: {mean_absolute_difference}",
        },
    ]

    comparison_summary = pd.DataFrame(summary_records)

    return comparison_summary, row_comparison


def build_saved_artifacts_summary(artifact_paths, artifact_keys):
    """
    Build a summary of saved inference artifacts.

    Parameters
    ----------
    artifact_paths : dict
        Artifact path registry.
    artifact_keys : list of str
        Artifact keys to summarize.

    Returns
    -------
    pandas.DataFrame
        Saved artifacts summary.
    """
    records = []

    for artifact_key in artifact_keys:
        path = Path(artifact_paths[artifact_key])

        records.append(
            {
                "artifact_key": artifact_key,
                "path": path.as_posix(),
                "exists": path.exists(),
                "file_size_mb": file_size_mb(path),
            }
        )

    return pd.DataFrame(records)


def build_inference_report(
    project_name,
    inference_output_version,
    serving_metadata,
    feature_summary,
    prediction_summary,
    comparison_summary=None,
    created_at=None,
):
    """
    Build a JSON-serializable inference report.

    Parameters
    ----------
    project_name : str
        Project name.
    inference_output_version : str
        Inference output version.
    serving_metadata : dict
        Serving model metadata.
    feature_summary : dict
        Feature loading summary.
    prediction_summary : dict
        Prediction summary.
    comparison_summary : pandas.DataFrame, optional
        Reproducibility comparison summary.
    created_at : str, optional
        Report creation timestamp.

    Returns
    -------
    dict
        Inference report.
    """
    report = {
        "project_name": project_name,
        "inference_output_version": inference_output_version,
        "created_at": created_at,
        "serving": {
            "recommended_model_version": serving_metadata.get("recommended_model_version"),
            "serving_model_version": serving_metadata.get("serving_model_version"),
            "uses_full_serving_model": serving_metadata.get("uses_full_serving_model"),
            "model_path": serving_metadata.get("model_path"),
            "config_path": serving_metadata.get("config_path"),
            "config_available": serving_metadata.get("config_available"),
        },
        "features": feature_summary,
        "predictions": prediction_summary,
    }

    if comparison_summary is not None:
        report["reproducibility"] = comparison_summary.to_dict("records")

    return report


def build_closure_checks(
    artifact_inventory,
    raw_schema_validation,
    feature_contract_validation,
    categorical_alignment_validation,
    model_contract_validation,
    prediction_output_validation,
    comparison_summary,
):
    """
    Build notebook closure checks.

    Parameters
    ----------
    artifact_inventory : pandas.DataFrame
        Artifact inventory.
    raw_schema_validation : pandas.DataFrame
        Raw schema validation.
    feature_contract_validation : pandas.DataFrame
        Feature contract validation.
    categorical_alignment_validation : pandas.DataFrame
        Categorical alignment validation.
    model_contract_validation : pandas.DataFrame
        Model contract validation.
    prediction_output_validation : pandas.DataFrame
        Prediction output validation.
    comparison_summary : pandas.DataFrame
        Reproducibility comparison summary.

    Returns
    -------
    pandas.DataFrame
        Closure criteria table.
    """
    checks = []

    required_artifacts_missing = artifact_inventory[
        (artifact_inventory["required"] == True)
        & (artifact_inventory["exists"] == False)
    ]

    checks.append(
        {
            "check": "required_artifacts_available",
            "passed": required_artifacts_missing.empty,
            "critical": True,
            "details": (
                "All required artifacts are available."
                if required_artifacts_missing.empty
                else f"Missing artifacts: {required_artifacts_missing['artifact_key'].tolist()}"
            ),
        }
    )

    validation_groups = {
        "raw_schema_validation_passed": raw_schema_validation,
        "feature_contract_validation_passed": feature_contract_validation,
        "categorical_alignment_validation_passed": categorical_alignment_validation,
        "model_contract_validation_passed": model_contract_validation,
        "prediction_output_validation_passed": prediction_output_validation,
        "src_matches_notebook_08": comparison_summary,
    }

    for check_name, validation_table in validation_groups.items():
        critical_failures = validation_table[
            (validation_table["critical"] == True)
            & (validation_table["passed"] == False)
        ]

        checks.append(
            {
                "check": check_name,
                "passed": critical_failures.empty,
                "critical": True,
                "details": (
                    "No critical failures."
                    if critical_failures.empty
                    else f"Failed checks: {critical_failures['check'].tolist()}"
                ),
            }
        )

    return pd.DataFrame(checks)
